# Force Update 2
services:
  - type: web
    name: book-recommendation-backend
    env: node
    buildCommand: cd myapp/backend && npm install
    startCommand: cd myapp/backend && npm start
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

staticSites:
  - name: book-recommendation-frontend
    buildCommand: cd myapp && npm install && npm run build
    publishDir: myapp/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
# Force update 02/15/2026 12:33:41
